name: atlantic_shores_south
library: library
weather: boem_era5_39.5_-74.0.csv
service_equipment:
  - ctv1.yaml
  - ctv2.yaml
  - ctv3.yaml
  - ctv4.yaml
  - ctv5.yaml
  - ctv6.yaml
  - ctv7.yaml
  - clv.yaml
  - jackup.yaml
  - dsv.yaml
layout: atlantic_shores_south_layout_base.csv
inflation_rate: 0
fixed_costs: Atlantic_Shores_South_fixed_costs.yaml
workday_start: 7
workday_end: 19
start_year: 2000
end_year: 2020
project_capacity: 3000
port_distance: 147
