# Site + Plant Parameters
site:
  depth: 34.93
  distance: 141
  distance_to_landfall: 89
  mean_windspeed: 8.37101822989067
plant:
  layout: custom
  num_turbines: 69
  row_spacing: 7.71
  substation_distance: 1
  turbine_spacing: 7.71

landfall:
  interconnection_distance: 9
  trench_length: 2
turbine: 15MW_generic
oss_design:
  num_substations: 1
# Vessels
array_cable_install_vessel: example_cable_lay_vessel
export_cable_install_vessel: example_cable_lay_vessel
export_cable_bury_vessel: example_cable_lay_vessel
oss_install_vessel: example_heavy_lift_vessel
spi_vessel: example_scour_protection_vessel
wtiv: example_wtiv
# Module Specific
OffshoreSubstationInstallation:
  feeder: example_heavy_feeder
  num_feeders: 1
array_system_design:
  cables:
  - XLPE_630mm_66kV
  - XLPE_185mm_66kV
  location_data: kitty_hawk_north_layout_base
export_system_design:
  cables: XLPE_1900mm_275kV
  percent_added_length: 0.0
scour_protection_design:
  cost_per_tonne: 40
  scour_protection_depth: 1
# Configured Phases
design_phases:
- MonopileDesign
- ScourProtectionDesign
- CustomArraySystemDesign
- ExportSystemDesign
- OffshoreSubstationDesign
install_phases:
  ArrayCableInstallation: 0
  ExportCableInstallation: 0
  MonopileInstallation: !!python/tuple
  - ScourProtectionInstallation
  - 0.5
  OffshoreSubstationInstallation: 0
  ScourProtectionInstallation: 0
  TurbineInstallation: !!python/tuple
  - MonopileInstallation
  - 0.1
# Project Inputs
project_parameters:
  turbine_capex: 1500
  commissioning: 0.01
  decommissioning: 0.15
  site_auction_price: 10592835
