name: COE_2022_fixed_bottom
library: library
random_seed: 1
weather: WTK_137m_lat41_03325_long-70_61667_2007to2013_time_series.csv
service_equipment:
  - ctv1.yaml
  - ctv2.yaml
  - ctv3.yaml
  - clv.yaml
  - jackup.yaml
  - dsv.yaml
layout: COE_2022_fixed_bottom_layout_base.csv
inflation_rate: 0
fixed_costs: COE_2022_fixed_bottom_fixed_costs.yaml
workday_start: 7
workday_end: 19
start_year: 2007
end_year: 2013
project_capacity: 600
port_distance: 116
